package org.example;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class AndersenAuthPostMsgTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:\\Downloads\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    WebDriver.Timeouts timeouts = driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.get("https://learn.andersenlab.com/");
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void andersenAuthPostMsg() {
    driver.get("https://learn.andersenlab.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("spiritusdentatus");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("237534096Gaz!~");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".iconsmall")).click();
  }
}
