package org.example;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class ProjectCreationGbTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "D:\\Downloads\\chromedriver_win32\\chromedriver.exe");
        driver = new ChromeDriver();
        WebDriver.Timeouts timeouts = driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
        driver.get("https://crm.geekbrains.space/user/login");
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void projectCreationGb() {
        driver.get("https://crm.geekbrains.space/user/login");
        driver.manage().window().setSize(new Dimension(1058, 812));
        driver.findElement(By.id("prependedInput")).click();
        driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
        driver.findElement(By.id("prependedInput2")).click();
        driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
        driver.findElement(By.id("_submit")).click();
        driver.findElement(By.xpath("//span[@class='title'][contains(text(),'Проекты')]")).click();
        driver.findElement(By.xpath("//span[contains(text(),'Мои проекты')]")).click();
        driver.findElement(By.linkText("Создать проект")).click();
        driver.findElement(By.xpath("//input[@data-ftid='crm_project_name']")).sendKeys("TestCase101");

        {
            WebElement element = driver.findElement(By.cssSelector(".select2-default > .select2-chosen"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.id(".select2-drop-mask"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.id("crm_project[businessUnit]")).click();
        {
            WebElement dropdown = driver.findElement(By.id("crm_project[businessUnit]"));
            dropdown.findElement(By.xpath("//option[. = 'Research & Development']")).click();
        }
        driver.findElement(By.cssSelector(".lang-ru")).click();
        driver.findElement(By.id("crm_project[curator]")).click();
        {
            WebElement dropdown = driver.findElement(By.id("crm_project[curator]"));
            dropdown.findElement(By.xpath("//option[. = 'Applanatest1 Applanatest1 Applanatest1']")).click();
        }
        driver.findElement(By.id("crm_project[rp]")).click();
        {
            WebElement dropdown = driver.findElement(By.id("crm_project[rp]"));
            dropdown.findElement(By.xpath("//option[. = 'Applanatest1 Applanatest1 Applanatest1']")).click();
        }
        driver.findElement(By.id("crm_project[administrator]")).click();
        {
            WebElement dropdown = driver.findElement(By.id("crm_project[administrator]"));
            dropdown.findElement(By.xpath("//option[. = 'Applanatest1 Applanatest1 Applanatest1']")).click();
        }
        driver.findElement(By.id("crm_project[manager]")).click();
        {
            WebElement dropdown = driver.findElement(By.id("crm_project[manager]"));
            dropdown.findElement(By.xpath("//option[. = 'Applanatest1 Applanatest1 Applanatest1']")).click();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#s2id_crm_project_contactMain-uid-61313d944588d .select2-chosen"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
//    {
//      WebElement element = driver.findElement(By.cssSelector("#s2id_crm_project_contactMain-uid-61313d944588d .select2-chosen"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).clickAndHold().perform();
//    }
        {
            WebElement element = driver.findElement(By.id("select2-drop-mask"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".lang-ru")).click();
        driver.findElement(By.cssSelector(".select2-focused")).sendKeys("Testova Testa");
        driver.findElement(By.cssSelector(".select2-focused")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        js.executeScript("window.scrollTo(0,0)");
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }

        driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
    }
}
